from datetime import date
from pathlib import Path

import typer
from jinja2 import Environment, FileSystemLoader
from rich.console import Console
from rich.table import Table

from forge.core.paths import find_project_root, docs_dir

app = typer.Typer(help="Documentation commands.")
console = Console()

REQUIRED_FIELDS = ["**Document ID:**", "**Version:**", "**Status:**", "**Created:**", "**Owner:**"]


@app.command("new")
def new_document(
    section: str = typer.Argument(...),
    name: str = typer.Argument(...),
    title: str = typer.Option(None, "--title", "-t"),
    document_id: str = typer.Option(None, "--id"),
    status: str = typer.Option("Draft", "--status"),
    owner: str = typer.Option("Founding Team", "--owner"),
):
    root = find_project_root()
    target_dir = root / "docs" / section
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / f"{name}.md"

    if path.exists():
        console.print(f"[red]Document already exists:[/red] {path.relative_to(root)}")
        raise typer.Exit(code=1)

    template_dir = Path(__file__).resolve().parents[1] / "templates"
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template("document.md.j2")

    content = template.render(
        title=title or name.replace("_", " "),
        document_id=document_id or name.upper().replace("_", "-"),
        version="0.1",
        status=status,
        created=date.today().isoformat(),
        owner=owner,
    )
    path.write_text(content, encoding="utf-8")
    console.print(f"[green]Created:[/green] {path.relative_to(root)}")


@app.command("index")
def update_index():
    root = find_project_root()
    docs = docs_dir()
    index_path = docs / "INDEX.md"
    lines = ["# Numera Documentation Index", "", "This file is generated by Numera Forge.", ""]

    for section in sorted([p for p in docs.iterdir() if p.is_dir()]):
        files = sorted(section.glob("*.md"))
        if not files:
            continue
        lines.append(f"## {section.name.title()}")
        lines.append("")
        for file in files:
            title = file.stem.replace("_", " ")
            rel = file.relative_to(docs)
            lines.append(f"- [{title}]({rel.as_posix()})")
        lines.append("")

    index_path.write_text("\n".join(lines), encoding="utf-8")
    console.print(f"[green]Updated:[/green] {index_path.relative_to(root)}")


@app.command("validate")
def validate_docs():
    root = find_project_root()
    docs = docs_dir()
    failures = []
    files = sorted(docs.rglob("*.md"))

    for file in files:
        if file.name.upper() in {"README.MD", "INDEX.MD"}:
            continue
        content = file.read_text(encoding="utf-8")
        missing = [field for field in REQUIRED_FIELDS if field not in content]
        if missing:
            failures.append((file.relative_to(root), missing))

    if failures:
        console.print("[red]Validation failed.[/red]")
        table = Table("File", "Missing fields")
        for rel, missing in failures:
            table.add_row(str(rel), ", ".join(missing))
        console.print(table)
        raise typer.Exit(code=1)

    console.print(f"[green]Validation passed.[/green] {len(files)} markdown files checked.")


@app.command("list")
def list_docs():
    root = find_project_root()
    docs = docs_dir()
    table = Table("Document", "Path")
    for file in sorted(docs.rglob("*.md")):
        table.add_row(file.stem.replace("_", " "), str(file.relative_to(root)))
    console.print(table)
